#!/bin/sh

export LA_SWAY_PRE_STARTUP_LOADED=$(($LA_SWAY_PRE_STARTUP_LOADED+1))

# follow xprofile
source $HOME/.xprofile

# cursor
export XCURSOR_THEME='Breeze_Adapta'

# language
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
export LC_CTYPE=en_US.UTF-8

# running programs natively under Wayland
# ref: https://github.com/swaywm/sway/wiki/Running-programs-natively-under-wayland
export XDG_SESSION_TYPE=wayland
# for firefox
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
